## Python Advanced Day 3

### NumPy Basics

In [ ]:
! pip install numpy

In [1]:
import numpy as np

In [2]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularl

In [3]:
# scalar/singular
a=np.array([1])
a.shape

(1,)

In [4]:
# vector
a=np.array([1,2,3,4,5])
a.shape

(5,)

In [7]:
# 2-D array
a=np.array(
        [
            [1,2],
            [3,4]
        ]
        )
a.shape

(2, 2)

In [8]:
a=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]
])
a.shape

(4, 3)

In [10]:
# access by indexes: array[row,col]
a[0,2]

3

In [11]:
a[3,2]

12

In [15]:
# slicing: array[r1:r2, c1:c2]
print(a)
print()
print(a[1:3, 0:2])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[[4 5]
 [7 8]]


In [16]:
a[:3, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [17]:
a[2:, 1:]

array([[ 8,  9],
       [11, 12]])

In [19]:
# filetr array values
print(a[a%3==0])

[ 3  6  9 12]


In [22]:
a[a>5]

array([ 6,  7,  8,  9, 10, 11, 12])

In [24]:
# 3-D arrays
a=np.array([
    [[1.2, 1.2, 1.3], [2.1, 2.2, 2.3], [3.1, 3.2, 3.3]],
    [[4.1, 4.2, 4.3], [5.1, 5.2, 5.3], [6.1, 6.2, 6.3]]
])
a.shape

(2, 3, 3)

In [25]:
a[1, 2, 1]

6.2

In [27]:
a=np.array([[10, 20], [3.14, 40]])
print(a.dtype)

float64


In [26]:
type(a)

numpy.ndarray

In [28]:
a

array([[10.  , 20.  ],
       [ 3.14, 40.  ]])

In [29]:
a=np.array([[10, 20], [3.14, 40]], dtype='float32')
print(a.dtype)

float32


In [30]:
a=np.array([[10, 20], [3.14, 40]], dtype='int64')
print(a.dtype)

int64


In [31]:
a

array([[10, 20],
       [ 3, 40]], dtype=int64)

#### Mathematical Operations on nparray

In [32]:
x=np.array([[10, 20], [30, 40]])
y=np.array([[5, 6], [7, 8]])

In [33]:
print(x+y)

[[15 26]
 [37 48]]


In [34]:
print(np.add(x,y))

[[15 26]
 [37 48]]


In [35]:
print(x-y)

[[ 5 14]
 [23 32]]


In [36]:
print(np.subtract(x,y))

[[ 5 14]
 [23 32]]


In [37]:
print(x*y)

[[ 50 120]
 [210 320]]


In [38]:
print(np.multiply(x,y))

[[ 50 120]
 [210 320]]


In [39]:
print(x/y)

[[2.         3.33333333]
 [4.28571429 5.        ]]


In [40]:
print(np.divide(x,y))

[[2.         3.33333333]
 [4.28571429 5.        ]]


In [41]:
print(np.sqrt(x))

[[3.16227766 4.47213595]
 [5.47722558 6.32455532]]


In [42]:
print(np.mean(x))

25.0


In [43]:
print(np.average(x))

25.0


In [44]:
print(np.average(x, weights=[[0.5, 1.5], [2, 3.5]]))

31.333333333333332


In [46]:
print(np.median(x))

25.0


In [47]:
print(np.mod(x,y))

[[0 2]
 [2 0]]


In [48]:
print(np.amax(x))

40


In [49]:
print(np.amin(x))

10


In [50]:
print(np.std(x))

11.180339887498949


In [51]:
print(np.var(x))

125.0


In [52]:
print(np.cov(x,y))

[[50.  50.   5.   5. ]
 [50.  50.   5.   5. ]
 [ 5.   5.   0.5  0.5]
 [ 5.   5.   0.5  0.5]]


In [58]:
# percentile
scores=np.array([18, 19, 22, 23, 21, 25, 21, 23, 29, 28, 27, 27, 27, 28, 21, 19, 17, 15, 26, 25, 27])
print(np.percentile(scores, 50, 0))

23.0


In [59]:
# Broadcasting
x=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]
])
y=np.array([10, 0, 100])

In [61]:
z=np.empty_like(x)
z

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [62]:
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [63]:
y

array([ 10,   0, 100])

In [64]:
z=x+y
z

array([[ 11,   2, 103],
       [ 14,   5, 106],
       [ 17,   8, 109],
       [ 20,  11, 112]])

In [65]:
z=x*13
z

array([[ 13,  26,  39],
       [ 52,  65,  78],
       [ 91, 104, 117],
       [130, 143, 156]])

In [66]:
z=x*y
z

array([[  10,    0,  300],
       [  40,    0,  600],
       [  70,    0,  900],
       [ 100,    0, 1200]])

In [68]:
z=x-5
z

array([[-4, -3, -2],
       [-1,  0,  1],
       [ 2,  3,  4],
       [ 5,  6,  7]])

In [74]:
for i in range(4):
    for j in range(3):
        if i==j:
            x[i, j] = 11
x

array([[11, 99, 99],
       [99, 11, 99],
       [99, 99, 11],
       [99, 99, 99]])

In [75]:
a=np.array([4,5,6], dtype='complex')
a

array([4.+0.j, 5.+0.j, 6.+0.j])

In [76]:
a.dtype

dtype('complex128')

In [77]:
x

array([[11, 99, 99],
       [99, 11, 99],
       [99, 99, 11],
       [99, 99, 99]])

In [78]:
x.shape

(4, 3)

In [79]:
x.ndim

2

In [80]:
x

array([[11, 99, 99],
       [99, 11, 99],
       [99, 99, 11],
       [99, 99, 99]])

In [81]:
x.reshape(2,6)

array([[11, 99, 99, 99, 11, 99],
       [99, 99, 11, 99, 99, 99]])

In [83]:
x.reshape(2,2,3)

array([[[11, 99, 99],
        [99, 11, 99]],

       [[99, 99, 11],
        [99, 99, 99]]])

In [84]:
x.itemsize

4

In [86]:
a=np.array([1,2,3,4,5], dtype='int64')
a.itemsize

8

In [89]:
a=np.zeros((3,4), dtype='int32')
a

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [91]:
a=np.ones((2,2,3,2))
a

array([[[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]]])

In [92]:
# generate arrays automatically

In [93]:
a=np.arange(10, 40)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [94]:
a.reshape(5,6)

array([[10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [95]:
a=np.linspace(50, 80, 15)
a

array([50.        , 52.14285714, 54.28571429, 56.42857143, 58.57142857,
       60.71428571, 62.85714286, 65.        , 67.14285714, 69.28571429,
       71.42857143, 73.57142857, 75.71428571, 77.85714286, 80.        ])

In [98]:
30/14

2.142857142857143

In [108]:
x=np.arange(1, 13).reshape((4,3))
z=np.arange(10,22).reshape((3,4))
w=np.dot(x,z)
print(x)
print()
print(z)
print()
print(w)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]

[[ 92  98 104 110]
 [218 233 248 263]
 [344 368 392 416]
 [470 503 536 569]]


In [111]:
# Random Numbers
np.random.randint(10000)

9536

In [112]:
np.random.randint(500,600)

571

In [113]:
np.random.randint(50, 90, 20)

array([61, 62, 58, 56, 89, 82, 57, 66, 67, 50, 81, 82, 63, 73, 87, 58, 50,
       62, 84, 80])

In [114]:
a=np.random.randint(20, 30, 12).reshape((3,4))
a

array([[27, 25, 27, 21],
       [27, 21, 22, 28],
       [26, 26, 29, 27]])

In [115]:
np.random.seed(42)
a=np.random.randint(20, 30, 12).reshape((3,4))
a

array([[26, 23, 27, 24],
       [26, 29, 22, 26],
       [27, 24, 23, 27]])

In [116]:
np.random.rand(12)

array([0.70807258, 0.02058449, 0.96990985, 0.83244264, 0.21233911,
       0.18182497, 0.18340451, 0.30424224, 0.52475643, 0.43194502,
       0.29122914, 0.61185289])

In [117]:
np.random.rand(12).reshape((4,3))

array([[0.13949386, 0.29214465, 0.36636184],
       [0.45606998, 0.78517596, 0.19967378],
       [0.51423444, 0.59241457, 0.04645041],
       [0.60754485, 0.17052412, 0.06505159]])

In [118]:
np.random.rand(3,2)

array([[0.94888554, 0.96563203],
       [0.80839735, 0.30461377],
       [0.09767211, 0.68423303]])

In [119]:
np.random.rand(3,2, 3)

array([[[0.44015249, 0.12203823, 0.49517691],
        [0.03438852, 0.9093204 , 0.25877998]],

       [[0.66252228, 0.31171108, 0.52006802],
        [0.54671028, 0.18485446, 0.96958463]],

       [[0.77513282, 0.93949894, 0.89482735],
        [0.59789998, 0.92187424, 0.0884925 ]]])

In [123]:
# exmaple
np.random.seed(42)
a=5
b=3
x=np.random.randint(0, 10, 9).reshape((3,3))
y=np.random.rand(3,3)
z=a*x+b*y
print(z)

[[31.00112583 15.42860045 36.95266542]
 [20.16923474 32.16599632 47.81565813]
 [10.0023363  32.97663468 36.85244453]]


In [124]:
np.mean(z)

29.262744043470928

In [126]:
np.cov(x,y)

array([[ 4.33333333,  1.83333333, -0.5       ,  0.48696531, -0.04140078,
        -0.64275264],
       [ 1.83333333,  6.33333333,  6.        ,  0.45471345,  1.06525697,
         0.65703153],
       [-0.5       ,  6.        ,  7.        ,  0.22175897,  1.21493473,
         1.11241914],
       [ 0.48696531,  0.45471345,  0.22175897,  0.06585161,  0.04379827,
        -0.03066202],
       [-0.04140078,  1.06525697,  1.21493473,  0.04379827,  0.21134582,
         0.18712576],
       [-0.64275264,  0.65703153,  1.11241914, -0.03066202,  0.18712576,
         0.25061398]])

In [127]:
# compare NumPy arrays with List

In [128]:
%%time
l1=[n for n in range(1000000)]
l2=[n for n in range(1000000)]
l3=l1+l2

CPU times: total: 203 ms
Wall time: 208 ms


In [130]:
%%time
x=np.random.rand(1000,1000)
y=np.random.rand(1000,1000)
z=x**2 + y**2

CPU times: total: 46.9 ms
Wall time: 46.2 ms


#### My Modules

In [131]:
import basicmath

In [132]:
basicmath.addition(23,56)

79

In [134]:
from basicmath import subtraction, sqr
subtraction(90, 32)

58

In [135]:
sqr(87)

7569

In [136]:
from basicmath import division as dv
dv(45, 0)

'Divisor Can Not be Zero!'

In [137]:
dv(45,3)

15.0

In [139]:
import scientificmath as sm

In [140]:
sm.area_circle(23)

1661.9025137490005

In [141]:
# check packages

In [145]:
import wonderfulmath.basicmath as bm

In [146]:
bm.division(78,4)

19.5

In [147]:
from wonderfulmath.advance import scientificmath as sm

In [148]:
sm.area_circle(34)

3631.681107549801

In [149]:
sm.PIE

3.141592653589793

In [152]:
sm.INFINITI

inf

In [153]:
sm.E

2.718281828459045

### Generators in Python

In [156]:
# generate values and yeild back

def generate_numbers():
    for i in range(1,11):
        yield i

In [158]:
num=generate_numbers()

In [159]:
for i in num:
    print(i)

1
2
3
4
5
6
7
8
9
10


In [160]:
num=generate_numbers()

In [172]:
next(num)

StopIteration: 

In [173]:
def random_generator():
    import random
    for _ in range(10):
        yield random.randint(1,100)

In [174]:
rg=random_generator()
next(rg)

72

In [175]:
for _ in range(5):
    rg=random_generator()
    print(list(rg))

[30, 34, 72, 92, 96, 29, 4, 22, 51, 34]
[98, 69, 57, 92, 37, 28, 66, 84, 72, 92]
[55, 53, 74, 48, 16, 96, 60, 88, 42, 34]
[21, 95, 43, 28, 58, 41, 44, 15, 3, 87]
[32, 72, 29, 10, 29, 24, 96, 48, 76, 49]


In [176]:
list(rg)

[]

In [177]:
rg=random_generator()
for _ in range(5):
    print(next(rg))

40
53
7
87
29


In [178]:
next(rg)

85

## Decorators

In [179]:
# func as an object

def message(msg):
    return msg.upper()

print(message('Hello Deloitte'))

HELLO DELOITTE


In [180]:
callout=message

In [181]:
callout('hello python')

'HELLO PYTHON'

In [182]:
print(callout)

<function message at 0x000001C269BB1B80>


In [183]:
# func as parameter to another func

def soft(text):
    return text.lower()
def loud(text):
    return text.upper()

def display(func):
    msg=func('Hi! I am deloitted!!!')
    print(msg)

In [184]:
display(soft)

hi! i am deloitted!!!


In [185]:
display(loud)

HI! I AM DELOITTED!!!


In [186]:
# return func from another func

def find_exp(x): # outer
    def exp(y): # inner
        return x**y
    return exp

In [187]:
exponential=find_exp(5)   # def exp(y): return 5**y

In [188]:
exponential(2)

25

#### Decorator Style

In [189]:
def outer(func):
    def inner(name):
        print('Start Inner')
        ret=func()
        print(name+' '+ret)
        print('End Inner')
    return inner

def message():
    return 'Welcome to Deloitte!!!'
def message_new():
    return 'Welcome to Deloitte USI!!!'

In [191]:
# option 1
call=outer(message)
'''
call=
def inner(name):
        print('Start Inner')
        ret=message()
        print(name+' '+ret)
        print('End Inner')
'''
print(call('Prateek'))

Start Inner
Prateek Welcome to Deloitte!!!
End Inner
None


In [192]:
call=outer(message_new)
call('Apoorva')

Start Inner
Apoorva Welcome to Deloitte USI!!!
End Inner


In [194]:
# option 2
outer(message)('Saurav')

Start Inner
Saurav Welcome to Deloitte!!!
End Inner


In [195]:
# option 3: decorator syntax
def outer(func):
    def inner(*args, **kwargs):
        print('Start Inner')
        ret=func()
        print(ret)
        print('End Inner')
    return inner

In [199]:
@outer
def  message():
    return 'Welcome to Python Training'
@outer
def message_new():
    return 'Python is Best!'

In [200]:
message()

Start Inner
Welcome to Python Training
End Inner


In [201]:
message_new()

Start Inner
Python is Best!
End Inner


In [202]:
def outer(func):
    def inner(*args, **kwargs):
        print('Inner Starts!')
        ret=func(*args, **kwargs)
        print('Inner Ends!')
        return ret
    return inner
@outer
def find_sum(*args):
    print('Calculating Sum...')
    return sum(args)

In [203]:
find_sum(10,20)

Inner Starts!
Calculating Sum...
Inner Ends!


30

In [204]:
find_sum(10,20,30,40,50)

Inner Starts!
Calculating Sum...
Inner Ends!


150

In [205]:
# write decorator func code that calculates running/execution time
# for any input function

In [214]:
import time
def timer(func):
    def inner():
        start=time.time()
        func()
        end=time.time()
        time_delta=round((end-start),2)
        print('Execution Time for '+func.__name__+' is:')
        print(str(time_delta*100)+' miliseconds')
    return inner

In [215]:
@timer
def run_for():
    for _ in range(10000):
        for _ in range(10000):
            pass
        pass
    return None

In [216]:
run_for()

Execution Time for run_for is:
101.0 miliseconds


In [217]:
@timer
def sum_list():
    import numpy as np
    l1=[n for n in range(1000000)]
    l2=[n for n in range(1000000)]
    l3=l1+l2
    print('Mean Result: ', np.mean(np.array(l3)))
    return None
sum_list()

Mean Result:  499999.5
Execution Time for sum_list is:
21.0 miliseconds
