## Python Adv Day 3

### Generators

In [7]:
# generate and yield

def generate_number():
    for i in range(1,11):
        yield i

In [8]:
numbers=generate_number()

In [9]:
print(numbers)

<generator object generate_number at 0x000001F77E072270>


In [10]:
for num in numbers:
    print(num)

1
2
3
4
5
6
7
8
9
10


In [14]:
def random_generator():
    import random
    for _ in range(10):
        yield random.randint(1,100)

In [21]:
for _ in range(5):
    rg=random_generator()
    print(list(rg))

[12, 14, 31, 20, 5, 87, 51, 3, 19, 52]
[21, 82, 88, 37, 89, 80, 73, 60, 39, 1]
[83, 24, 2, 58, 14, 22, 59, 21, 63, 96]
[5, 62, 22, 85, 85, 4, 62, 22, 8, 27]
[52, 10, 94, 49, 97, 99, 72, 43, 73, 54]


In [20]:
list(rg)

[]

In [25]:
rg2=random_generator()

In [26]:
for _ in range(10):
    print(next(rg2))

98
29
57
5
26
66
99
61
80
17


In [27]:
next(rg2)

StopIteration: 

## Decorators

In [32]:
# func as object
def message(msg):
    return msg.upper()

print(message('Hello deloitte'))

HELLO DELOITTE


In [33]:
say=message

In [34]:
say('hello python')

'HELLO PYTHON'

In [35]:
# func as parameter to another func

def soft(text):
    return text.lower()
def loud(text):
    return text.upper()

def display(func):
    msg=func("Hi! I am feeling good at Deloitte")
    print(msg)

In [36]:
display(soft)

hi! i am feeling good at deloitte


In [37]:
display(loud)

HI! I AM FEELING GOOD AT DELOITTE


In [38]:
# Return function from another function

def find_exp(x):
    def exp(y):
        return x**y
    return exp


In [40]:
exponential=find_exp(5) # def exp(y): return 5**y

In [42]:
exponential(2)

25

In [43]:
exponential_again=find_exp(9) # def exp(y): return 9**y

exponential_again(3)

729

In [44]:
# Decorator style

In [57]:
def outer(func):
    def inner(name):
        print('Start Inner')
        ret=func()
        print(name+' '+ret)
        print('End Inner')
    return inner

def message():
    return 'Welcome to Deloitte!'
def message_new():
    return 'Welcome to Deloitte USI'

In [61]:
# option 1:
call=outer(message)
'''
call=
def inner(name):
        print('Start Inner')
        ret=message()
        print(name+' '+ret)
        print('End Inner')
'''

call('Prateek')

Start Inner
Prateek Welcome to Deloitte!
End Inner


In [62]:
# option 2:
outer(message_new)('Raj')

Start Inner
Raj Welcome to Deloitte USI
End Inner


In [76]:
# option 3: decorator syntax

def outer(func):
    def inner(*args, **kwargs):
        print('Start Inner')
        ret=func()
        print(ret)
        print('End Inner')
    return inner

@outer
def message():
    return 'Welcome to Python Training!!!'
@outer
def message_new():
    return 'Python is best!!!'

In [77]:
message()

Start Inner
Welcome to Python Training!!!
End Inner


In [78]:
message_new()

Start Inner
Python is best!!!
End Inner


In [83]:
def outer(func):
    def inner(*args, **kwargs):
        print('Inner Starts!')
        ret=func(*args, **kwargs)
        print('Inner Ends!')
        return ret
    return inner

@outer
def find_sum(*args):
    print('Finding Sum...')
    return sum(args)

In [88]:
print('Sum= ', find_sum(10,20))

Inner Starts!
Finding Sum...
Inner Ends!
Sum=  30


In [89]:
print('Sum= ', find_sum(10,20, 50, 80, 90, 70))

Inner Starts!
Finding Sum...
Inner Ends!
Sum=  320


In [12]:
# Example Timer

import math
import time
def timer(func):
    def inner(*args, **kwargs):
        start=time.time()
        func()
        end=time.time()
        print('Time to Execute by '+func.__name__+' is: '
              +str(round((end-start),2))+' seconds')
    return inner

@timer
def run_for():
    for _ in range(10000):
        for _ in range(10000):
            pass
        pass
    return None

In [13]:
run_for()

Time to Execute by run_for is: 2.92 seconds


In [3]:
from db_learn import *

In [4]:
@insert
def add_values(roll, name, city):
    return 'insert into stud values({0},"{1}","{2}")'.format(roll, name, city)

In [5]:
add_values(roll=103, name='Raj',city='Jaipur')

Starting DB Connection...
Inserting Values...
Data Inserted!
Closing DB Connection...
Connections Closed!


In [6]:
import colorama
from colorama import Fore, Back, Style

In [17]:
print(Fore.RED+'My RED Text')
print(Fore.BLUE+'My BLUE Text')
print(Back.YELLOW+'My YELLOW Background Text in BLUE color')
print(Style.DIM+'Dimming Text')
print(Back.BLACK+Fore.WHITE+'My BLACK Background Text in WHITE color')
print(Style.RESET_ALL)
print('Normal Text')

My RED Text
My BLUE Text
My YELLOW Background Text in BLUE color
Dimming Text
My BLACK Background Text in WHITE color

Normal Text


# Numpy

In [ ]:
! pip install numpy

In [ ]:
! conda install numpy

In [1]:
import numpy as np

In [2]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularl

In [3]:
a=np.array([1]) # singular


In [5]:
a.shape

(1,)

In [7]:
# 1-D array
a=np.array([1,2,3,4,5]) # vector
a.shape

(5,)

In [8]:
# 2-D array
a=np.array([
    [1,2],
    [3,4]
])
a.shape

(2, 2)

In [12]:
a=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12],
    [13,14,15]
])
a.shape

(5, 3)

In [14]:
# array indexing
a[2,1] # array[row, col]

8

In [20]:
# index ranging
a[:3, 2:3] # array[row_range, col_range]

array([[3],
       [6],
       [9]])

In [21]:
# filter arrays
a[a%5==0]

array([ 5, 10, 15])

In [23]:
a[a>10]

array([11, 12, 13, 14, 15])

In [24]:
# 3-D array

a=np.array([
    [ [1,2], [3,4], [5,6] ],
    [ [10,20], [30,40], [50,60] ],
    [ [100,200], [300,400], [500,600] ]
])
a.shape

(3, 3, 2)

In [25]:
a[1,2,0]

50

In [26]:
a[a>100]

array([200, 300, 400, 500, 600])

In [27]:
# datatype
a.dtype

dtype('int32')

In [33]:
a[0,0,0]

1

In [32]:
a.dtype

dtype('int32')

In [37]:
a=np.array([1.25,2,4,5], dtype='int32')
a.dtype

dtype('int32')

In [38]:
a

array([1, 2, 4, 5])

In [39]:
a=np.array([1.25,2,4,5])
a.dtype

dtype('float64')

### NumPy mathematical operations

In [41]:
x=np.array([[1,2],[3,4]])
y=np.array([[10,20],[30,40]])

In [42]:
print(x+y)

[[11 22]
 [33 44]]


In [43]:
print(np.add(x,y))

[[11 22]
 [33 44]]


In [44]:
print(x-y)

[[ -9 -18]
 [-27 -36]]


In [45]:
print(np.subtract(x,y))

[[ -9 -18]
 [-27 -36]]


In [46]:
print(x*y)

[[ 10  40]
 [ 90 160]]


In [47]:
print(np.multiply(x,y))

[[ 10  40]
 [ 90 160]]


In [48]:
print(x/y)

[[0.1 0.1]
 [0.1 0.1]]


In [49]:
print(np.divide(x,y))

[[0.1 0.1]
 [0.1 0.1]]


In [50]:
print(np.sqrt(y))

[[3.16227766 4.47213595]
 [5.47722558 6.32455532]]


In [51]:
print(np.mean(y))

25.0


In [53]:
print(np.median(y))

25.0


In [57]:
print(np.mod(y,x))

[[0 0]
 [0 0]]


In [58]:
print(np.std(y))

11.180339887498949


In [60]:
print(np.var(y))

125.0


In [61]:
print(np.cov(x,y))

[[ 0.5  0.5  5.   5. ]
 [ 0.5  0.5  5.   5. ]
 [ 5.   5.  50.  50. ]
 [ 5.   5.  50.  50. ]]


In [62]:
print(np.amin(y))

10


In [63]:
print(np.amax(y))

40


In [64]:
print(np.average(y))

25.0


In [65]:
print(np.average(y, weights=[[8,9],[13,14]]))

27.5


In [75]:
a=np.array([5,6,7,9,5,3,1,6,8,4,8,6,5,3])
print(np.percentile(a, 100,0))

9.0


In [76]:
# Broadcasting

In [77]:
x=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]
])

y=np.array([1,0,1])

In [80]:
z=np.empty_like(x)

In [81]:
z

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [82]:
for i in range(4):
    z[i,:]=x[i,:]+y
print(z)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [83]:
print(x+y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [84]:
print(x*y)

[[ 1  0  3]
 [ 4  0  6]
 [ 7  0  9]
 [10  0 12]]


In [86]:
y=np.array([1.45, 5.67, 3.14])

In [87]:
print(x/y)

[[0.68965517 0.35273369 0.95541401]
 [2.75862069 0.88183422 1.91082803]
 [4.82758621 1.41093474 2.86624204]
 [6.89655172 1.94003527 3.82165605]]


In [88]:
print(x*y)

[[ 1.45 11.34  9.42]
 [ 5.8  28.35 18.84]
 [10.15 45.36 28.26]
 [14.5  62.37 37.68]]


In [89]:
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [90]:
x-32

array([[-31, -30, -29],
       [-28, -27, -26],
       [-25, -24, -23],
       [-22, -21, -20]])

In [91]:
x.shape

(4, 3)

In [92]:
x.ndim

2

In [93]:
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [95]:
x.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [96]:
x.dtype

dtype('int32')

In [97]:
x.itemsize

4

In [99]:
a=np.array([12,3,4,5],dtype='float64')

In [100]:
a.itemsize

8

In [102]:
a=np.zeros((4,5))
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [104]:
a=np.ones((3,2,2))
a

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [105]:
# creating NP arrays from other structures

In [106]:
a=[1,2,3,4,5,6,7,8,9]
type(a)

list

In [110]:
ar=np.asarray(a).reshape((3,3))
type(ar)

numpy.ndarray

In [111]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [112]:
# NumPy generator

In [113]:
a=np.arange(10,100)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [118]:
a=np.arange(5.5, 101.5 , 2.5)
a

array([  5.5,   8. ,  10.5,  13. ,  15.5,  18. ,  20.5,  23. ,  25.5,
        28. ,  30.5,  33. ,  35.5,  38. ,  40.5,  43. ,  45.5,  48. ,
        50.5,  53. ,  55.5,  58. ,  60.5,  63. ,  65.5,  68. ,  70.5,
        73. ,  75.5,  78. ,  80.5,  83. ,  85.5,  88. ,  90.5,  93. ,
        95.5,  98. , 100.5])

In [120]:
a=np.linspace(50, 90, 20)
a

array([50.        , 52.10526316, 54.21052632, 56.31578947, 58.42105263,
       60.52631579, 62.63157895, 64.73684211, 66.84210526, 68.94736842,
       71.05263158, 73.15789474, 75.26315789, 77.36842105, 79.47368421,
       81.57894737, 83.68421053, 85.78947368, 87.89473684, 90.        ])

In [123]:
# Dot Product

In [124]:
z

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

In [130]:
z=z.reshape((3,4))
z

array([[ 2,  2,  4,  5],
       [ 5,  7,  8,  8],
       [10, 11, 11, 13]])

In [131]:
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [132]:
y=np.dot(x,z)
y

array([[ 42,  49,  53,  60],
       [ 93, 109, 122, 138],
       [144, 169, 191, 216],
       [195, 229, 260, 294]])

### Random Numbers in NumPy

In [133]:
np.random.randint(100)

2

In [134]:
np.random.randint(70,100)

79

In [136]:
np.random.randint(50,200,40).reshape(8,5)

array([[166, 141,  99, 127,  77],
       [ 95, 102,  66,  79,  65],
       [ 51, 120, 155, 159,  96],
       [159,  57, 185,  87,  52],
       [154, 106, 166,  60,  53],
       [128, 112, 129, 181,  63],
       [157, 127,  95, 126,  64],
       [ 78, 154,  58, 109, 117]])

In [137]:
np.random.seed(42)

In [138]:
np.random.randint(50,200,40).reshape(8,5)

array([[152, 142,  64, 156, 121],
       [ 70, 152, 171, 124, 137],
       [166, 149, 153, 180, 199],
       [102,  51, 137,  87, 179],
       [ 70, 107,  71, 138,  98],
       [108,  64, 100, 157, 104],
       [113, 180, 100, 184,  70],
       [122,  67, 181, 138, 109]])

In [139]:
np.random.rand(10)

array([0.56328822, 0.3854165 , 0.01596625, 0.23089383, 0.24102547,
       0.68326352, 0.60999666, 0.83319491, 0.17336465, 0.39106061])

In [140]:
np.random.rand(5,3)

array([[0.18223609, 0.75536141, 0.42515587],
       [0.20794166, 0.56770033, 0.03131329],
       [0.84228477, 0.44975413, 0.39515024],
       [0.92665887, 0.727272  , 0.32654077],
       [0.57044397, 0.52083426, 0.96117202]])

In [148]:
np.random.seed(42)
a=5
b=3
x=np.random.randint(200,5000,900).reshape(30,30)
y=np.random.rand(30,30)

In [149]:
print('X= ',x)
print('Y= ',y)

X=  [[1060 3972 3292  666 4626 3644 3371 3119  330 1885  969 2591 2633 1384
  4755 3585 4317 3104  674 1282 2758 2247 2947 1175 2006  389 2934 3205
  4858 2099]
 [1467 1728 3402 3756 4090  846 3088 2635  800 2563 2261  441 2241 3024
  2812 1563 1678 2756  975 4214  234 3352 2155 1785 4143 3273 1221 3661
  2813 4043]
 [1700 4998  361 4497 2181 1195 3542 4751 3998 1475 1216  537 1078 1276
  4193  579  692 2262 4084  264 2768 2227 2895 1695  591 4714 4674 3761
  2478 3299]
 [ 400 3304 4798 2654 3845 1004 2931 2973 1770 2890 4040 1228  702 4693
  1070 4688  406 1684 1063 2990  763 4391 1957 1878 3442 4836 1259 1922
  3514 3357]
 [2825 2929 1797 3260 2893 3827 1563 2181 1863 1729 2238 3502 2437 1506
  4229 2875 1482  909 4944 4613 3948 4979  863 2198 3645 3943 1695 3504
  3963 2053]
 [4859 1491 3781 3657 1836 3896 3199 3352  898 2360 4297 4937 1054 3674
  1907 2977 1933 3710  402 3455 4418 4696  966 4589 2527 3131  397 2130
  3782  808]
 [3472 1347 4482 3597 2711 1994  859 3011 1569 2186  3

In [150]:
z=a*x*82+b*y**2
print(z)

[[ 434601.56494632 1628521.55535784 1349721.23321086  273061.44469333
  1896660.88364946 1494040.1902083  1382110.35851716 1278790.09893319
   135302.47584727  772851.02103796  397290.48204557 1062310.64034809
  1079532.69203718  567440.07054996 1949551.03099625 1469850.76777007
  1769971.12162885 1272640.00098394  276342.28180034  525622.60653348
  1130780.95812655  921271.45596711 1208272.55301532  481751.50055946
   822460.06980448  159490.99632482 1202941.10430944 1314050.53966048
  1991781.62705034  860592.61912515]
 [ 601472.57003122  708480.60976842 1394820.03846857 1539962.90973656
  1676902.11125     346860.04662235 1266082.54384932 1080352.27015904
   328000.80757879 1050831.04881992  927010.47760947  180810.00899651
   918810.33707157 1239841.93372098 1152920.00006437  640830.33366509
   687980.47561493 1129960.8663821   399752.53840307 1727740.35986664
    95940.36112957 1374321.63172427  883550.6135032   731850.15134198
  1698630.61410455 1341930.0595221   500610.09333711 

In [151]:
print(np.cov(z,y))

[[ 3.00362919e+11  6.32135979e+09 -1.61004164e+10 ...  9.44369083e+02
   3.64897992e+03 -1.24160786e+04]
 [ 6.32135979e+09  2.27885716e+11 -5.61691181e+09 ...  2.28505791e+04
   6.14091407e+03 -5.36936437e+04]
 [-1.61004164e+10 -5.61691181e+09  4.03009204e+11 ...  3.88746694e+04
  -3.21861726e+04  1.38294242e+04]
 ...
 [ 9.44369083e+02  2.28505791e+04  3.88746694e+04 ...  8.47139215e-02
  -2.59104261e-02 -8.79408363e-03]
 [ 3.64897992e+03  6.14091407e+03 -3.21861726e+04 ... -2.59104261e-02
   8.21894367e-02  1.81837009e-02]
 [-1.24160786e+04 -5.36936437e+04  1.38294242e+04 ... -8.79408363e-03
   1.81837009e-02  9.12709984e-02]]


In [152]:
np.mean(z)

1089043.928016484

In [153]:
z.shape

(30, 30)

In [1]:
import numpy as np

In [2]:
np.random.seed(18)
a=5
b=3
x=np.random.randint(1,150000,90000).reshape(300,300)
y=np.random.rand(300,300)

In [3]:
%%time
z=np.dot(x,y)
z.shape

CPU times: total: 15.6 ms
Wall time: 41 ms


(300, 300)

In [8]:
%%time
l1=[x for x in range(900000)]
l2=[x for x in range(900000)]
l3=l1+l2

CPU times: total: 93.8 ms
Wall time: 93 ms
