### NumPy Basics

In [2]:
import numpy as np

In [5]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularl

In [15]:
a=np.array([1]) #singular
a.shape

(1,)

In [16]:
a=np.array([1,2,3,4,5]) #scalar
a.shape

(5,)

In [25]:
a=np.array([
    [1,2],
    [3,4]
])
#2D array
a.shape

(2, 2)

In [41]:
a=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12],
    [13,14,15]
])
a.shape

(5, 3)

In [42]:
a[0,1]

2

In [43]:
a[:3,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [47]:
print(a[a%5==0])

[ 5 10 15]


In [35]:
a=np.array([
    [[1.1, 1.2, 1.3],[2.1, 2.2, 2.3]],
    [[3.1, 3.2, 3.3],[4.1, 4.2, 4.3]]
])
a.shape

(2, 2, 3)

In [36]:
a[1,1,2]

4.3

In [54]:
# datatype

a=np.array([[1,2],[3.2,4]])
print(a.dtype)

float64


In [55]:
a

array([[1. , 2. ],
       [3.2, 4. ]])

In [58]:
a=np.array([[1,2],[3.74,4]], dtype='int64')
print(a.dtype)

int64


In [59]:
a

array([[1, 2],
       [3, 4]], dtype=int64)

##### Mathematical op

In [60]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])

In [61]:
print(x+y)

[[ 6  8]
 [10 12]]


In [62]:
print(np.add(x,y))

[[ 6  8]
 [10 12]]


In [63]:
print(x-y)

[[-4 -4]
 [-4 -4]]


In [64]:
print(np.subtract(x,y))

[[-4 -4]
 [-4 -4]]


In [65]:
print(x*y)

[[ 5 12]
 [21 32]]


In [66]:
print(np.multiply(x,y))

[[ 5 12]
 [21 32]]


In [69]:
print(x/y)

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [70]:
print(np.divide(x,y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [72]:
print(np.sqrt(y))

[[2.23606798 2.44948974]
 [2.64575131 2.82842712]]


In [74]:
print(np.mean(y))

6.5


In [76]:
print(np.median(x))

2.5


In [80]:
print(np.mod(y,x))

[[0 0]
 [1 0]]


In [84]:
print(np.std(y))

1.118033988749895


In [87]:
print(np.var(y))

1.25


In [88]:
print(np.cov(x,y))

[[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]


In [89]:
print(np.amin(y))

5


In [90]:
print(np.amax(y))

8


In [91]:
print(np.average(y))

6.5


In [94]:
print(np.average(y, weights=[[8,9],[3,7]]))

6.333333333333333


In [104]:
a=np.array([5,6,7,8,1,2,3,9,10,30,28])
print(np.percentile(a, 65, 0))

8.5


In [105]:
# Broadcasting

x=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]
])

y=np.array([1,0,1])


In [106]:
z=np.empty_like(x)

In [107]:
z

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [108]:
for i in range(4):
    z[i,:] = x[i,:]+y
print(z)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [109]:
print(x+y) # broadcasting automatically done

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [110]:
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [111]:
y=np.array([10, 2, 100])

In [112]:
print(x*y)

[[  10    4  300]
 [  40   10  600]
 [  70   16  900]
 [ 100   22 1200]]


In [113]:
print(x/y)

[[0.1  1.   0.03]
 [0.4  2.5  0.06]
 [0.7  4.   0.09]
 [1.   5.5  0.12]]


In [114]:
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [117]:
x-22

array([[-21, -20, -19],
       [-18, -17, -16],
       [-15, -14, -13],
       [-12, -11, -10]])

In [122]:
a=np.array([4,5,6], dtype='complex')
print(a)
print(a.dtype)

[4.+0.j 5.+0.j 6.+0.j]
complex128


In [124]:
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [125]:
x.shape

(4, 3)

In [126]:
x.ndim

2

In [128]:
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [131]:
x.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [133]:
x.itemsize #bytes for each element

4

In [134]:
a=np.array([1,2,3,4], dtype='int8')
a.itemsize

1

In [135]:
a=np.array([1,2,3,4], dtype='int64')
a.itemsize

8

In [140]:
a=np.zeros((4,5))
a

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [142]:
a=np.ones((3,4,2))
a

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [150]:
a=[10,20,30,40]
type(a)

list

In [151]:
a=np.asarray(a)
type(a)

numpy.ndarray

In [152]:
a

array([10, 20, 30, 40])

In [155]:
a=np.arange(10,100)

In [156]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [157]:
a=np.linspace(60, 80, 15)
a

array([60.        , 61.42857143, 62.85714286, 64.28571429, 65.71428571,
       67.14285714, 68.57142857, 70.        , 71.42857143, 72.85714286,
       74.28571429, 75.71428571, 77.14285714, 78.57142857, 80.        ])

In [158]:
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [163]:
z=z.reshape(3,4)

In [164]:
y=np.dot(x,z)

In [165]:
y

array([[ 42,  49,  53,  60],
       [ 93, 109, 122, 138],
       [144, 169, 191, 216],
       [195, 229, 260, 294]])

#### Random Numbers

In [175]:
np.random.randint(100)

77

In [180]:
np.random.randint(50,100)

72

In [182]:
np.random.randint(50,100,12)

array([70, 79, 90, 80, 87, 72, 73, 91, 97, 96, 79, 82])

In [186]:
np.random.randint(50,100,12).reshape(3,4)

array([[83, 58, 82, 55],
       [82, 71, 63, 95],
       [64, 99, 82, 91]])

In [192]:
np.random.seed(42) 

In [193]:
np.random.randint(50,100,12).reshape(3,4)

array([[88, 78, 64, 92],
       [57, 70, 88, 68],
       [72, 60, 60, 73]])

In [177]:
np.random.rand(10)

array([0.22198423, 0.08326208, 0.97782416, 0.3519799 , 0.47558398,
       0.43691864, 0.82889364, 0.89506003, 0.24952395, 0.24818859])

In [195]:
np.random.rand(5,3)

array([[0.52083426, 0.96117202, 0.84453385],
       [0.74732011, 0.53969213, 0.58675117],
       [0.96525531, 0.60703425, 0.27599918],
       [0.29627351, 0.16526694, 0.01563641],
       [0.42340148, 0.39488152, 0.29348817]])

In [196]:
# Example
np.random.seed(42)
a=5
b=3
x=np.random.randint(0,10,9).reshape(3,3)
y=np.random.rand(3,3)
print(x,y)

[[6 3 7]
 [4 6 9]
 [2 6 7]] [[3.33708611e-01 1.42866818e-01 6.50888473e-01]
 [5.64115790e-02 7.21998772e-01 9.38552709e-01]
 [7.78765841e-04 9.92211559e-01 6.17481510e-01]]


In [197]:
z=a*x+b*y
print(z)

[[31.00112583 15.42860045 36.95266542]
 [20.16923474 32.16599632 47.81565813]
 [10.0023363  32.97663468 36.85244453]]


In [198]:
np.cov(z,y)

array([[ 1.23534957e+02,  5.24272078e+01, -1.90908633e+01,
         2.63238138e+00, -7.56091002e-02, -3.30574925e+00],
       [ 5.24272078e+01,  1.92193155e+02,  1.79763626e+02,
         2.40496206e+00,  5.96032232e+00,  3.84653491e+00],
       [-1.90908633e+01,  1.79763626e+02,  2.10628100e+02,
         1.01680878e+00,  6.63605091e+00,  6.31393764e+00],
       [ 2.63238138e+00,  2.40496206e+00,  1.01680878e+00,
         6.58516095e-02,  4.37982729e-02, -3.06620169e-02],
       [-7.56091002e-02,  5.96032232e+00,  6.63605091e+00,
         4.37982729e-02,  2.11345815e-01,  1.87125760e-01],
       [-3.30574925e+00,  3.84653491e+00,  6.31393764e+00,
        -3.06620169e-02,  1.87125760e-01,  2.50613978e-01]])

In [199]:
np.mean(z)

29.262744043470928

In [200]:
np.mean(x)

5.555555555555555

In [201]:
np.mean(y)

0.4949887552310488

In [202]:
np.dot(x,y)

array([[ 2.17693776,  9.96867814, 11.04335953],
       [ 1.68031281, 13.83336394, 13.79220373],
       [ 1.01133806, 11.56320718, 11.25546377]])

In [203]:
a*x**2 + b*y**2

array([[180.33408431,  45.06123278, 246.27096741],
       [ 80.0095468 , 181.56384668, 407.64264356],
       [ 20.00000182, 182.95345134, 246.14385024]])

In [213]:
x=np.random.rand(100,100)

In [214]:
y=np.random.rand(100,100)

In [215]:
y.shape

(100, 100)

In [216]:
%%time
z=a*x**2 + b*y**2

CPU times: total: 0 ns
Wall time: 0 ns


In [217]:
z.shape

(100, 100)

In [218]:
%%time
z=np.dot(x,y)
z.shape

CPU times: total: 31.2 ms
Wall time: 58.1 ms


(100, 100)

In [225]:
%%time
l1=[x for x in range(1000000)]
l2=[x for x in range(1000000)]
l1+l2

CPU times: total: 125 ms
Wall time: 135 ms


[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,


In [224]:
%%time
k=np.random.randint(1000000)
w=np.random.randint(1000000)
k+w

CPU times: total: 0 ns
Wall time: 0 ns


1342801